defaults:
  -
    scope:
      path: "projects"
    values:
      layout: "project"
      
prose:
  media: "images"
  metadata:
    projects/_posts:
      - name: "title"
        field:
          element: "text"
          value: "title"
          label: "Title"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
